class CreateAiEngineeringSystem < Formula
  desc "Bootstrap projects from the AI Engineering System"
  homepage "https://github.com/supanut9/ai-engineering-system"
  url "https://github.com/supanut9/ai-engineering-system/archive/refs/tags/ai-engineering-system-v0.7.1.tar.gz"
  sha256 "7e2d8f5d1729a2fd06e06048e7cbcab2a739692f9bb42f12db31bc6380f05588"
  license "MIT"
  version "0.7.1"

  # init-project.sh gates on bash 4+, which macOS's system bash (3.2) does not satisfy.
  depends_on "bash"
  depends_on "git"

  def install
    # Drop the whole system tree into libexec so init-project.sh can resolve
    # SYSTEM_ROOT (templates/, claude/, codex/, tooling/, etc.) at runtime.
    libexec.install Dir["*"]

    # Thin wrapper that execs init-project.sh through Homebrew's bash 5+.
    (bin/"create-ai-engineering-system").write <<~SH
      #!/usr/bin/env bash
      # Auto-generated by Homebrew formula. Do not edit.
      exec "#{Formula["bash"].opt_bin}/bash" "#{libexec}/scripts/init-project.sh" "$@"
    SH

    # Convenience short alias.
    bin.install_symlink "create-ai-engineering-system" => "ai-eng-init"
  end

  test do
    output = shell_output("#{bin}/create-ai-engineering-system --help")
    assert_match "Usage:", output
    assert_match "--stack", output
    assert_match "--package-manager", output
  end
end
